const newYorkData = {
  current_condition: [
    {
      FeelsLikeC: "25",
      FeelsLikeF: "76",
      cloudcover: "0",
      humidity: "79",
      localObsDateTime: "2022-08-31 10:01 AM",
      observation_time: "02:01 PM",
      precipInches: "0.0",
      precipMM: "0.0",
      pressure: "1010",
      pressureInches: "30",
      temp_C: "22",
      temp_F: "72",
      uvIndex: "6",
      visibility: "16",
      visibilityMiles: "9",
      weatherCode: "113",
      weatherDesc: [
        {
          value: "Sunny",
        },
      ],
      weatherIconUrl: [
        {
          value: "",
        },
      ],
      winddir16Point: "WNW",
      winddirDegree: "298",
      windspeedKmph: "4",
      windspeedMiles: "2",
    },
  ],
  nearest_area: [
    {
      areaName: [
        {
          value: "Long Island City",
        },
      ],
      country: [
        {
          value: "United States of America",
        },
      ],
      latitude: "40.745",
      longitude: "-73.949",
      population: "0",
      region: [
        {
          value: "New York",
        },
      ],
      weatherUrl: [
        {
          value: "",
        },
      ],
    },
  ],
  request: [
    {
      query: "Lat 40.73 and Lon -73.99",
      type: "LatLon",
    },
  ],
  weather: [
    {
      astronomy: [
        {
          moon_illumination: "22",
          moon_phase: "Waxing Crescent",
          moonrise: "10:39 AM",
          moonset: "09:43 PM",
          sunrise: "06:22 AM",
          sunset: "07:30 PM",
        },
      ],
      avgtempC: "26",
      avgtempF: "79",
      date: "2022-08-31",
      hourly: [
        {
          DewPointC: "21",
          DewPointF: "70",
          FeelsLikeC: "26",
          FeelsLikeF: "79",
          HeatIndexC: "26",
          HeatIndexF: "79",
          WindChillC: "24",
          WindChillF: "75",
          WindGustKmph: "20",
          WindGustMiles: "12",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "10",
          chanceofovercast: "87",
          chanceofrain: "62",
          chanceofremdry: "0",
          chanceofsnow: "0",
          chanceofsunshine: "0",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "85",
          humidity: "85",
          precipInches: "0.1",
          precipMM: "2.1",
          pressure: "1008",
          pressureInches: "30",
          tempC: "24",
          tempF: "75",
          time: "0",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "353",
          weatherDesc: [
            {
              value: "Light rain shower",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "WSW",
          winddirDegree: "254",
          windspeedKmph: "12",
          windspeedMiles: "7",
        },
        {
          DewPointC: "20",
          DewPointF: "68",
          FeelsLikeC: "25",
          FeelsLikeF: "77",
          HeatIndexC: "25",
          HeatIndexF: "77",
          WindChillC: "23",
          WindChillF: "74",
          WindGustKmph: "19",
          WindGustMiles: "12",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "10",
          chanceofovercast: "38",
          chanceofrain: "0",
          chanceofremdry: "80",
          chanceofsnow: "0",
          chanceofsunshine: "72",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "27",
          humidity: "82",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1007",
          pressureInches: "30",
          tempC: "23",
          tempF: "74",
          time: "300",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "116",
          weatherDesc: [
            {
              value: "Partly cloudy",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "WNW",
          winddirDegree: "297",
          windspeedKmph: "14",
          windspeedMiles: "9",
        },
        {
          DewPointC: "18",
          DewPointF: "64",
          FeelsLikeC: "22",
          FeelsLikeF: "71",
          HeatIndexC: "24",
          HeatIndexF: "76",
          WindChillC: "22",
          WindChillF: "71",
          WindGustKmph: "17",
          WindGustMiles: "11",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "0",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "90",
          chanceofsnow: "0",
          chanceofsunshine: "93",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "4",
          humidity: "79",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1008",
          pressureInches: "30",
          tempC: "22",
          tempF: "71",
          time: "600",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Clear",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "WNW",
          winddirDegree: "294",
          windspeedKmph: "12",
          windspeedMiles: "7",
        },
        {
          DewPointC: "16",
          DewPointF: "60",
          FeelsLikeC: "25",
          FeelsLikeF: "78",
          HeatIndexC: "25",
          HeatIndexF: "78",
          WindChillC: "24",
          WindChillF: "75",
          WindGustKmph: "18",
          WindGustMiles: "11",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "10",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "84",
          chanceofsnow: "0",
          chanceofsunshine: "86",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "10",
          humidity: "61",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1009",
          pressureInches: "30",
          tempC: "24",
          tempF: "75",
          time: "900",
          uvIndex: "6",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "WNW",
          winddirDegree: "302",
          windspeedKmph: "15",
          windspeedMiles: "10",
        },
        {
          DewPointC: "15",
          DewPointF: "60",
          FeelsLikeC: "30",
          FeelsLikeF: "85",
          HeatIndexC: "30",
          HeatIndexF: "85",
          WindChillC: "29",
          WindChillF: "85",
          WindGustKmph: "22",
          WindGustMiles: "14",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "97",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "86",
          chanceofsnow: "0",
          chanceofsunshine: "90",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "22",
          humidity: "43",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1009",
          pressureInches: "30",
          tempC: "29",
          tempF: "85",
          time: "1200",
          uvIndex: "7",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "WNW",
          winddirDegree: "289",
          windspeedKmph: "19",
          windspeedMiles: "12",
        },
        {
          DewPointC: "10",
          DewPointF: "51",
          FeelsLikeC: "31",
          FeelsLikeF: "88",
          HeatIndexC: "31",
          HeatIndexF: "88",
          WindChillC: "33",
          WindChillF: "91",
          WindGustKmph: "27",
          WindGustMiles: "17",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "96",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "90",
          chanceofsnow: "0",
          chanceofsunshine: "87",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "8",
          humidity: "26",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1008",
          pressureInches: "30",
          tempC: "33",
          tempF: "91",
          time: "1500",
          uvIndex: "8",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "WNW",
          winddirDegree: "299",
          windspeedKmph: "23",
          windspeedMiles: "15",
        },
        {
          DewPointC: "9",
          DewPointF: "48",
          FeelsLikeC: "29",
          FeelsLikeF: "83",
          HeatIndexC: "29",
          HeatIndexF: "83",
          WindChillC: "30",
          WindChillF: "86",
          WindGustKmph: "23",
          WindGustMiles: "14",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "96",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "88",
          chanceofsnow: "0",
          chanceofsunshine: "86",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "7",
          humidity: "27",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1009",
          pressureInches: "30",
          tempC: "30",
          tempF: "86",
          time: "1800",
          uvIndex: "8",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "WNW",
          winddirDegree: "297",
          windspeedKmph: "20",
          windspeedMiles: "13",
        },
        {
          DewPointC: "10",
          DewPointF: "50",
          FeelsLikeC: "26",
          FeelsLikeF: "79",
          HeatIndexC: "26",
          HeatIndexF: "79",
          WindChillC: "26",
          WindChillF: "79",
          WindGustKmph: "12",
          WindGustMiles: "8",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "91",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "81",
          chanceofsnow: "0",
          chanceofsunshine: "88",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "10",
          humidity: "36",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1011",
          pressureInches: "30",
          tempC: "26",
          tempF: "79",
          time: "2100",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Clear",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "WNW",
          winddirDegree: "293",
          windspeedKmph: "8",
          windspeedMiles: "5",
        },
      ],
      maxtempC: "33",
      maxtempF: "91",
      mintempC: "22",
      mintempF: "71",
      sunHour: "13.0",
      totalSnow_cm: "0.0",
      uvIndex: "6",
    },
    {
      astronomy: [
        {
          moon_illumination: "34",
          moon_phase: "Waxing Crescent",
          moonrise: "11:49 AM",
          moonset: "10:10 PM",
          sunrise: "06:23 AM",
          sunset: "07:28 PM",
        },
      ],
      avgtempC: "25",
      avgtempF: "78",
      date: "2022-09-01",
      hourly: [
        {
          DewPointC: "11",
          DewPointF: "52",
          FeelsLikeC: "25",
          FeelsLikeF: "77",
          HeatIndexC: "25",
          HeatIndexF: "77",
          WindChillC: "24",
          WindChillF: "76",
          WindGustKmph: "13",
          WindGustMiles: "8",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "15",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "91",
          chanceofsnow: "0",
          chanceofsunshine: "88",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "11",
          humidity: "43",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1011",
          pressureInches: "30",
          tempC: "24",
          tempF: "76",
          time: "0",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Clear",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "WSW",
          winddirDegree: "250",
          windspeedKmph: "9",
          windspeedMiles: "5",
        },
        {
          DewPointC: "11",
          DewPointF: "52",
          FeelsLikeC: "25",
          FeelsLikeF: "76",
          HeatIndexC: "25",
          HeatIndexF: "76",
          WindChillC: "23",
          WindChillF: "74",
          WindGustKmph: "18",
          WindGustMiles: "11",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "10",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "87",
          chanceofsnow: "0",
          chanceofsunshine: "89",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "6",
          humidity: "46",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1011",
          pressureInches: "30",
          tempC: "23",
          tempF: "74",
          time: "300",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Clear",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "W",
          winddirDegree: "274",
          windspeedKmph: "11",
          windspeedMiles: "7",
        },
        {
          DewPointC: "11",
          DewPointF: "51",
          FeelsLikeC: "22",
          FeelsLikeF: "71",
          HeatIndexC: "24",
          HeatIndexF: "76",
          WindChillC: "22",
          WindChillF: "71",
          WindGustKmph: "20",
          WindGustMiles: "13",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "0",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "89",
          chanceofsnow: "0",
          chanceofsunshine: "89",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "7",
          humidity: "49",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1011",
          pressureInches: "30",
          tempC: "22",
          tempF: "71",
          time: "600",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Clear",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "WNW",
          winddirDegree: "289",
          windspeedKmph: "14",
          windspeedMiles: "9",
        },
        {
          DewPointC: "10",
          DewPointF: "51",
          FeelsLikeC: "25",
          FeelsLikeF: "76",
          HeatIndexC: "25",
          HeatIndexF: "76",
          WindChillC: "23",
          WindChillF: "74",
          WindGustKmph: "22",
          WindGustMiles: "14",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "10",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "86",
          chanceofsnow: "0",
          chanceofsunshine: "88",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "0",
          humidity: "44",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1014",
          pressureInches: "30",
          tempC: "23",
          tempF: "74",
          time: "900",
          uvIndex: "6",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "NW",
          winddirDegree: "311",
          windspeedKmph: "19",
          windspeedMiles: "12",
        },
        {
          DewPointC: "8",
          DewPointF: "46",
          FeelsLikeC: "28",
          FeelsLikeF: "82",
          HeatIndexC: "28",
          HeatIndexF: "82",
          WindChillC: "29",
          WindChillF: "84",
          WindGustKmph: "24",
          WindGustMiles: "15",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "93",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "82",
          chanceofsnow: "0",
          chanceofsunshine: "85",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "0",
          humidity: "27",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1015",
          pressureInches: "30",
          tempC: "29",
          tempF: "84",
          time: "1200",
          uvIndex: "7",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "NW",
          winddirDegree: "310",
          windspeedKmph: "21",
          windspeedMiles: "13",
        },
        {
          DewPointC: "8",
          DewPointF: "46",
          FeelsLikeC: "29",
          FeelsLikeF: "84",
          HeatIndexC: "29",
          HeatIndexF: "84",
          WindChillC: "31",
          WindChillF: "88",
          WindGustKmph: "22",
          WindGustMiles: "14",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "92",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "88",
          chanceofsnow: "0",
          chanceofsunshine: "91",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "0",
          humidity: "24",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1014",
          pressureInches: "30",
          tempC: "31",
          tempF: "88",
          time: "1500",
          uvIndex: "8",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "NW",
          winddirDegree: "308",
          windspeedKmph: "19",
          windspeedMiles: "12",
        },
        {
          DewPointC: "7",
          DewPointF: "44",
          FeelsLikeC: "27",
          FeelsLikeF: "81",
          HeatIndexC: "27",
          HeatIndexF: "81",
          WindChillC: "29",
          WindChillF: "84",
          WindGustKmph: "21",
          WindGustMiles: "13",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "90",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "89",
          chanceofsnow: "0",
          chanceofsunshine: "89",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "0",
          humidity: "25",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1015",
          pressureInches: "30",
          tempC: "29",
          tempF: "84",
          time: "1800",
          uvIndex: "7",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "NW",
          winddirDegree: "322",
          windspeedKmph: "18",
          windspeedMiles: "11",
        },
        {
          DewPointC: "6",
          DewPointF: "42",
          FeelsLikeC: "24",
          FeelsLikeF: "76",
          HeatIndexC: "24",
          HeatIndexF: "76",
          WindChillC: "24",
          WindChillF: "75",
          WindGustKmph: "19",
          WindGustMiles: "12",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "15",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "89",
          chanceofsnow: "0",
          chanceofsunshine: "88",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "0",
          humidity: "30",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1018",
          pressureInches: "30",
          tempC: "24",
          tempF: "75",
          time: "2100",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Clear",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "N",
          winddirDegree: "355",
          windspeedKmph: "14",
          windspeedMiles: "9",
        },
      ],
      maxtempC: "31",
      maxtempF: "88",
      mintempC: "22",
      mintempF: "71",
      sunHour: "13.0",
      totalSnow_cm: "0.0",
      uvIndex: "7",
    },
    {
      astronomy: [
        {
          moon_illumination: "42",
          moon_phase: "First Quarter",
          moonrise: "01:01 PM",
          moonset: "10:44 PM",
          sunrise: "06:24 AM",
          sunset: "07:27 PM",
        },
      ],
      avgtempC: "24",
      avgtempF: "75",
      date: "2022-09-02",
      hourly: [
        {
          DewPointC: "6",
          DewPointF: "44",
          FeelsLikeC: "22",
          FeelsLikeF: "71",
          HeatIndexC: "24",
          HeatIndexF: "75",
          WindChillC: "22",
          WindChillF: "71",
          WindGustKmph: "15",
          WindGustMiles: "10",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "0",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "87",
          chanceofsnow: "0",
          chanceofsunshine: "85",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "0",
          humidity: "37",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1019",
          pressureInches: "30",
          tempC: "22",
          tempF: "71",
          time: "0",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Clear",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "NNE",
          winddirDegree: "22",
          windspeedKmph: "12",
          windspeedMiles: "7",
        },
        {
          DewPointC: "7",
          DewPointF: "45",
          FeelsLikeC: "20",
          FeelsLikeF: "68",
          HeatIndexC: "20",
          HeatIndexF: "68",
          WindChillC: "20",
          WindChillF: "68",
          WindGustKmph: "11",
          WindGustMiles: "7",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "0",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "88",
          chanceofsnow: "0",
          chanceofsunshine: "93",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "0",
          humidity: "43",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1020",
          pressureInches: "30",
          tempC: "20",
          tempF: "68",
          time: "300",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Clear",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "NE",
          winddirDegree: "36",
          windspeedKmph: "8",
          windspeedMiles: "5",
        },
        {
          DewPointC: "7",
          DewPointF: "44",
          FeelsLikeC: "19",
          FeelsLikeF: "65",
          HeatIndexC: "19",
          HeatIndexF: "65",
          WindChillC: "19",
          WindChillF: "65",
          WindGustKmph: "12",
          WindGustMiles: "7",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "0",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "87",
          chanceofsnow: "0",
          chanceofsunshine: "92",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "0",
          humidity: "45",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1022",
          pressureInches: "30",
          tempC: "19",
          tempF: "65",
          time: "600",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Clear",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "NNE",
          winddirDegree: "27",
          windspeedKmph: "8",
          windspeedMiles: "5",
        },
        {
          DewPointC: "6",
          DewPointF: "43",
          FeelsLikeC: "21",
          FeelsLikeF: "69",
          HeatIndexC: "21",
          HeatIndexF: "69",
          WindChillC: "21",
          WindChillF: "69",
          WindGustKmph: "9",
          WindGustMiles: "6",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "0",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "85",
          chanceofsnow: "0",
          chanceofsunshine: "94",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "0",
          humidity: "38",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1024",
          pressureInches: "30",
          tempC: "21",
          tempF: "69",
          time: "900",
          uvIndex: "6",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "NE",
          winddirDegree: "39",
          windspeedKmph: "8",
          windspeedMiles: "5",
        },
        {
          DewPointC: "8",
          DewPointF: "46",
          FeelsLikeC: "27",
          FeelsLikeF: "81",
          HeatIndexC: "27",
          HeatIndexF: "81",
          WindChillC: "29",
          WindChillF: "83",
          WindGustKmph: "5",
          WindGustMiles: "3",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "86",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "85",
          chanceofsnow: "0",
          chanceofsunshine: "86",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "0",
          humidity: "27",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1024",
          pressureInches: "30",
          tempC: "29",
          tempF: "83",
          time: "1200",
          uvIndex: "7",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "ENE",
          winddirDegree: "78",
          windspeedKmph: "4",
          windspeedMiles: "3",
        },
        {
          DewPointC: "9",
          DewPointF: "47",
          FeelsLikeC: "29",
          FeelsLikeF: "84",
          HeatIndexC: "29",
          HeatIndexF: "84",
          WindChillC: "30",
          WindChillF: "87",
          WindGustKmph: "10",
          WindGustMiles: "6",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "88",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "89",
          chanceofsnow: "0",
          chanceofsunshine: "91",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "2",
          humidity: "26",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1023",
          pressureInches: "30",
          tempC: "30",
          tempF: "87",
          time: "1500",
          uvIndex: "8",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "SSE",
          winddirDegree: "155",
          windspeedKmph: "9",
          windspeedMiles: "6",
        },
        {
          DewPointC: "9",
          DewPointF: "49",
          FeelsLikeC: "26",
          FeelsLikeF: "78",
          HeatIndexC: "26",
          HeatIndexF: "78",
          WindChillC: "26",
          WindChillF: "79",
          WindGustKmph: "17",
          WindGustMiles: "11",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "78",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "84",
          chanceofsnow: "0",
          chanceofsunshine: "94",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "2",
          humidity: "34",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1023",
          pressureInches: "30",
          tempC: "26",
          tempF: "79",
          time: "1800",
          uvIndex: "7",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Sunny",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "SSE",
          winddirDegree: "148",
          windspeedKmph: "15",
          windspeedMiles: "9",
        },
        {
          DewPointC: "12",
          DewPointF: "53",
          FeelsLikeC: "25",
          FeelsLikeF: "77",
          HeatIndexC: "25",
          HeatIndexF: "77",
          WindChillC: "23",
          WindChillF: "74",
          WindGustKmph: "19",
          WindGustMiles: "12",
          chanceoffog: "0",
          chanceoffrost: "0",
          chanceofhightemp: "10",
          chanceofovercast: "0",
          chanceofrain: "0",
          chanceofremdry: "87",
          chanceofsnow: "0",
          chanceofsunshine: "87",
          chanceofthunder: "0",
          chanceofwindy: "0",
          cloudcover: "5",
          humidity: "48",
          precipInches: "0.0",
          precipMM: "0.0",
          pressure: "1025",
          pressureInches: "30",
          tempC: "23",
          tempF: "74",
          time: "2100",
          uvIndex: "1",
          visibility: "10",
          visibilityMiles: "6",
          weatherCode: "113",
          weatherDesc: [
            {
              value: "Clear",
            },
          ],
          weatherIconUrl: [
            {
              value: "",
            },
          ],
          winddir16Point: "SE",
          winddirDegree: "144",
          windspeedKmph: "15",
          windspeedMiles: "9",
        },
      ],
      maxtempC: "30",
      maxtempF: "87",
      mintempC: "19",
      mintempF: "65",
      sunHour: "13.0",
      totalSnow_cm: "0.0",
      uvIndex: "6",
    },
  ],
};

// get the time
const currentTime = new Date()
console.log(currentTime.getHours())
// Date.prototype.getHours()